version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /cmd/app
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /handlers
    schedule:
      interval: daily
