name: golang-pipeline
on:
  push:
    branches:
      - "main"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build app
        working-directory: cmd/app
        run: go build
  deploy:
    runs-on: ubuntu-latest
    needs: build

    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: set version
        id: set-version
        run: |
          echo "docker-tag=$(echo $GITHUB_REF_NAME)" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set version for environment
        run: |
          sed -i 's/GOLANG_VER/${{ steps.set-version.outputs.docker-tag }}/g' Dockerfile

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: jorikvl/project-hive-box:${{ steps.set-version.outputs.docker-tag }}
