name: create release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "app version"
        required: true
        default: v0.0.0

permissions:
  contents: read

jobs:
  check_vers:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: check_vers
        run: |
          if [[ '${{ github.event.inputs.version }}' =~ v[0-9]+.[0-9]+.[0-9]+ ]]
          then
            echo ${{ github.event.inputs.version }}
          else
            exit 1
          fi
  deploy:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest
    needs: check_vers

    if: github.ref == 'refs/heads/main'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_DEPLOY_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set version for environment
        run: |
          sed -i 's/v[0-9]+.[0-9]+.[0-9]+/${{ github.event.inputs.version }}/g' Dockerfile

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: jorikvl/project-hive-box:${{ github.event.inputs.version }}

      - name: update kubernetes manifest
        run: |
          git config --global user.name "Jorik-VanLooy"
          git config --global user.email "jorik716@gmail.com"
          git fetch
          git checkout main

          sed -i 's/v[0-9]\+\.[0-9]\+\.[0-9]\+/${{ github.event.inputs.version }}/g' kubernetes/backend.yaml
          git add kubernetes/*
          git commit -a -m "bump: update version"
          git push -f

          git tag ${{ github.event.inputs.version }}
          git push --tags
