name: Test Go

on: pull_request



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22.4
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
      # You can test your matrix by printing the current Go version
      - name: Test go app
        run: |
          for file in $(ls -d */); do
            go test
          done
        working-directory: src/

