name: Test handlers

on: pull_request



permissions:
  contents: read

jobs:
  test-handlers:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Go 1.22.4
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: 1.22.4      
      - name: golangci-lint
        working-directory: handlers
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run
      # You can test your matrix by printing the current Go version
      - name: Test go app
        env:
          VERSION: "$GITHUB_REF_NAME"
        run: |
          go test
        working-directory: handlers

